---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ftcoza/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    