---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qfpuksur/public_html/ft8.co.za/mbarc
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    